export const dataset = [
  { folder: "crescent", file: "crescent10.jpg" },
  { folder: "crescent", file: "crescent11.jpg" },
  { folder: "crescent", file: "crescent12.jpg" },
  { folder: "crescent", file: "crescent13.jpg" },
  { folder: "crescent", file: "crescent14.jpg" },
  { folder: "crescent", file: "crescent15.jpg" },
  { folder: "crescent", file: "crescent_1_1_20906204.png" },
  { folder: "crescent", file: "crescent_1_1_3756940021.png" },
  { folder: "crescent", file: "crescent_1_1_404693984.png" },
  { folder: "crescent", file: "crescent_1_1_505703428.png" },
  { folder: "crescent", file: "sky1.png" },
  { folder: "crescent", file: "sky2.png" },
  { folder: "crescent", file: "sky3.png" },
  { folder: "crescent", file: "sky7.png" },
  { folder: "no_crescent", file: "no_crescent12.jpg" },
  { folder: "no_crescent", file: "no_crescent13.jpg" },
  { folder: "no_crescent", file: "no_crescent14.jpg" },
  { folder: "no_crescent", file: "no_crescent15.jpg" },
  { folder: "no_crescent", file: "no_crescent16.jpg" },
  { folder: "no_crescent", file: "no_crescent18.jpg" },
  { folder: "no_crescent", file: "no_crescent19.jpg" },
  { folder: "no_crescent", file: "no_crescent20.jpg" },
  { folder: "no_crescent", file: "no_crescent22.jpg" },
  { folder: "no_crescent", file: "no_crescent_11.jpg" },
  { folder: "no_crescent", file: "no_crescent_1_1_3145031925.png" },
  { folder: "no_crescent", file: "no_crescent_1_2_1738403280.png" },
  { folder: "no_crescent", file: "sky4.png" },
  { folder: "no_crescent", file: "sky5.png" },
  { folder: "no_crescent", file: "sky6.png" },
  { folder: "no_crescent", file: "sky8.png" }
];

